services:
  kiot-db:
    image: mongo:7
    container_name: kiot-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - kiot_data:/data/db
    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: notification-service
    restart: always
    environment:
      - MONGO_URL=mongodb://kiot-db:27017/kiot-db
      - REDIS_HOST=redis
      - PORT=5001
    depends_on:
      - kiot-db
      - redis
    ports:
      - "5001:5001"
    networks:
      - app-network

  backend-seed:
    container_name: backend-seed
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: "no"
    environment:
      - MONGO_URL=mongodb://kiot-db:27017/kiot-db
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - kiot-db
      - redis
    command: node seed.js
    networks:
      - app-network

  backend: &backend
    container_name: "backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    expose:
      - "5000"
    environment:
      - MONGO_URL=mongodb://kiot-db:27017/kiot-db
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - kiot-db
      - redis
      - backend-seed
    networks:
      - app-network
    command: node src/server.js

  backend-1:
    <<: *backend
    container_name: backend-1

  backend-2:
    <<: *backend
    container_name: backend-2

  backend-lb:
    image: nginx:latest
    container_name: backend-lb
    depends_on:
      - backend
      - backend-1
      - backend-2
    ports:
      - "5000:80"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: kiot-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - notification-service
      - backend-lb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  kiot_data:
